In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Bengaluru_House_Data.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [4]:
for col in df.columns:
    print(df[col].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                 540
Sarjapur  Road             399
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ...
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
PronsAs     1
NantsGa     1
Vemit S     1
Shamzm      1
SJces R     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200       843
1100       221
1500       205
2400       196
600        180
          ...
1369         1
5665.84      1
2920         1
6688         1
1331.95      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
219.00      1
32.93       1
988.00      1
94.28       1
43.04       1
Name: count, Length: 1994, dtype: int64
********************

In [5]:
df.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [6]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [7]:
df['location']=df['location'].fillna('Sarjapur Road')

In [8]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [9]:
df['size']=df['size'].fillna('2 BHK')

In [10]:
bath_median=df['bath'].median()
bath_median

np.float64(2.0)

In [11]:
df['bath']=df['bath'].fillna('bath_median')

In [12]:
 df['bhk']=df['size'].str.split().str.get(0).astype(int)

In [13]:
df=df.drop(columns=['size'])
df.head()

                   location total_sqft bath   price  bhk
0  Electronic City Phase II       1056  2.0   39.07    2
1          Chikka Tirupathi       2600  5.0  120.00    4
2               Uttarahalli       1440  2.0   62.00    3
3        Lingadheeranahalli       1521  3.0   95.00    3
4                  Kothanur       1200  2.0   51.00    2

In [14]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [15]:
def convertRange(x):
    temp=x.split('-')
    if len(temp)==2:
        return (float(temp[0])+float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [16]:
df['total_sqft']=df['total_sqft'].apply(convertRange)

In [17]:
df.head()

                   location  total_sqft bath   price  bhk
0  Electronic City Phase II      1056.0  2.0   39.07    2
1          Chikka Tirupathi      2600.0  5.0  120.00    4
2               Uttarahalli      1440.0  2.0   62.00    3
3        Lingadheeranahalli      1521.0  3.0   95.00    3
4                  Kothanur      1200.0  2.0   51.00    2

In [20]:
df.sample(10)

                 location  total_sqft bath   price  bhk
7530             Nagavara      1125.0  2.0   44.50    2
6154   Lingadheeranahalli      2245.0  4.0  154.00    4
1541       Thigalarapalya      1297.0  2.0  103.00    2
13179    LB Shastri Nagar      1200.0  2.0   75.00    2
9118       Kanakpura Road      1570.0  3.0   65.93    3
9335          Thanisandra       933.0  2.0   55.00    2
5279      Nagadevanahalli      1250.0  2.0   65.00    3
3171      Electronic City      1000.0  2.0   22.00    2
8773           Whitefield      1227.0  2.0   70.00    2
9820          Hennur Road      1305.0  2.0  110.00    3

In [21]:
df['price_per_sqft']=df['price']*100000 /df['total_sqft']
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [24]:
location_count=df['location'].value_counts()
print(df['location'])

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316               Richards Town
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13320, dtype: object

In [26]:
location_count_lessthan_10=location_count[location_count<=10]
location_count_lessthan_10

location
Basapura             10
Dairy Circle         10
Naganathapura        10
Dodsworth Layout     10
Ganga Nagar          10
                     ..
Sabari Nagar          1
Ashraya Layout        1
Shauhardha Layout     1
Kudlu Village,        1
Chikkanahalli         1
Name: count, Length: 1065, dtype: int64

In [28]:
df['location']=df['location'].apply(lambda x: 'other' if x in location_count_lessthan_10 else x )
df['location'].value_counts()

location
other                        2901
Whitefield                    540
Sarjapur  Road                399
Electronic City               302
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [29]:
df=df[((df['total_sqft']/df['bhk']) >=300)]
df.describe()

         total_sqft         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544    111.382401      2.650838     6303.979357
std     1261.271296    152.077329      0.976678     4162.237981
min      300.000000      8.440000      1.000000      267.829813
25%     1116.000000     49.000000      2.000000     4210.526316
50%     1300.000000     70.000000      3.000000     5294.117647
75%     1700.000000    115.000000      3.000000     6916.666667
max    52272.000000   3600.000000     16.000000   176470.588235

In [30]:
df.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [31]:
df.head(4)

                   location  total_sqft bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0  2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0  5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0  2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0  3.0   95.00    3     6245.890861

In [32]:
df['location'].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli',
       'Lingadheeranahalli', 'Kothanur', 'Whitefield', 'Old Airport Road',
       'Rajaji Nagar', 'Marathahalli', '7th Phase JP Nagar', 'Gottigere',
       'Sarjapur', 'Mysore Road', 'Bisuvanahalli',
       'Raja Rajeshwari Nagar', 'other', 'Kengeri', 'Binny Pete',
       'Thanisandra', 'Bellandur', 'Electronic City', 'Ramagondanahalli',
       'Yelahanka', 'Hebbal', 'Kasturi Nagar', 'Kanakpura Road',
       'Electronics City Phase 1', 'Kundalahalli', 'Chikkalasandra',
       'Murugeshpalya', 'Sarjapur  Road', 'Doddathoguru', 'KR Puram',
       'Bhoganhalli', 'Lakshminarayana Pura', 'Begur Road', 'Devanahalli',
       'Varthur', 'Bommanahalli', 'Gunjur', 'Hegde Nagar', 'Haralur Road',
       'Hennur Road', 'Kothannur', 'Kalena Agrahara', 'ISRO Layout',
       'Garudachar Palya', 'EPIP Zone', 'Dasanapura', 'Kasavanhalli',
       'Sanjay nagar', 'Domlur', 'Sarjapura - Attibele Road',
       'Yeshwanthpur', 'Chandapura', 'Nagarbhavi', 'Ramamurthy Nagar',
       'Malleshwaram', 'Akshaya Nagar', 'Shampura', 'Kadugodi',
       'LB Shastri Nagar', 'Hormavu', 'Kudlu Gate', '8th Phase JP Nagar',
       'Bommasandra Industrial Area', 'Anandapura',
       'Vishveshwarya Layout', 'Kengeri Satellite Town', 'Kannamangala',
       ' Devarachikkanahalli', 'Hulimavu', 'Mahalakshmi Layout',
       'Hosa Road', 'Attibele', 'CV Raman Nagar', 'Nagavara',
       'Hebbal Kempapura', 'Vijayanagar', 'Pattandur Agrahara',
       'HSR Layout', 'Nagasandra', 'Kogilu', 'Panathur',
       'Padmanabhanagar', '1st Block Jayanagar', 'Kammasandra',
       'Dasarahalli', 'Magadi Road', 'Koramangala', 'Dommasandra',
       'Budigere', 'Kalyan nagar', 'OMBR Layout', 'Horamavu Agara',
       'Ambedkar Nagar', 'Talaghattapura', 'Balagere', 'Jigani',
       'Gollarapalya Hosahalli', 'Old Madras Road', 'Kaggadasapura',
       '9th Phase JP Nagar', 'Jakkur', 'TC Palaya', 'Singasandra',
       'AECS Layout', 'Mallasandra', 'Begur', 'JP Nagar', 'Malleshpalya',
       'Munnekollal', 'Giri Nagar', 'Kaval Byrasandra', 'Kaggalipura',
       '6th Phase JP Nagar', 'Ulsoor', 'Thigalarapalya',
       'Somasundara Palya', 'Basaveshwara Nagar', 'Bommasandra',
       'Ardendale', 'Harlur', 'Kodihalli', 'Narayanapura',
       'Bannerghatta Road', 'Hennur', '5th Phase JP Nagar', 'Kodigehaali',
       'Billekahalli', 'Jalahalli', 'Mahadevpura', 'Anekal', 'Sompura',
       'Dodda Nekkundi', 'Hosur Road', 'Battarahalli', 'Ambalipura',
       'Hoodi', 'Brookefield', 'Yelenahalli', 'Vittasandra',
       '2nd Stage Nagarbhavi', 'Vidyaranyapura', 'Amruthahalli',
       'Kodigehalli', 'Subramanyapura', 'Kereguddadahalli', 'Kambipura',
       'Banashankari Stage III', 'Sector 7 HSR Layout', 'Rajiv Nagar',
       'Arekere', 'Mico Layout', 'Kammanahalli', 'Banashankari',
       'Chikkabanavar', 'HRBR Layout', 'Nehru Nagar', 'Kanakapura',
       'Konanakunte', 'R.T. Nagar', 'Tumkur Road', 'Vasanthapura',
       'GM Palaya', 'Jalahalli East', 'Hosakerehalli', 'Indira Nagar',
       'Kodichikkanahalli', 'Varthur Road', 'Anjanapura', 'Abbigere',
       'Tindlu', 'Gubbalala', 'Parappana Agrahara', 'Cunningham Road',
       'Kudlu', 'Vishwapriya Layout', 'Banashankari Stage VI', 'Cox Town',
       'Kathriguppe', 'Yelahanka New Town', 'Sahakara Nagar',
       'Rachenahalli', 'Yelachenahalli', 'Green Glen Layout',
       'Thubarahalli', 'Horamavu Banaswadi', '1st Phase JP Nagar',
       'NGR Layout', 'Seegehalli', 'BEML Layout', 'NRI Layout', 'ITPL',
       'Margondanahalli', 'Babusapalaya', 'Iblur Village', 'Ananth Nagar',
       'Channasandra', 'Choodasandra', 'Kaikondrahalli', 'Neeladri Nagar',
       'Frazer Town', 'Cooke Town', 'Doddakallasandra', 'Chamrajpet',
       'Rayasandra', 'Pai Layout', 'Banashankari Stage V', 'Sonnenahalli',
       'Benson Town', '2nd Phase Judicial Layout', 'Poorna Pragna Layout',
       'Judicial Layout', 'Banashankari Stage II', 'Karuna Nagar',
       'Banjara Layout', 'Marsur', 'Basavangudi', 'Bannerghatta',
       'Bommenahalli', 'HBR Layout', 'Laggere', 'Prithvi Layout',
       'Banaswadi', 'Sector 2 HSR Layout', 'Badavala Nagar',
       'Nagavarapalya', 'BTM Layout', '5th Block Hbr Layout',
       'BTM 2nd Stage', 'Hoskote', 'Doddaballapur', 'Kumaraswami Layout',
       'Sarakki Nagar', 'Thyagaraja Nagar', 'Bharathi Nagar',
       'HAL 2nd Stage', 'Sultan Palaya', 'Kadubeesanahalli',
       'Shivaji Nagar', 'Kenchenahalli'], dtype=object)